### ISSUE TITLE
Exception when running an interface method

### ISSUE THREAD

**Issue by kellerkind** [LEW21/pydbus#12]
Script:

	if __name__ == '__main__':

	    t = MediaDeviceThread()
	    t.daemon = False
	    t.start()

Using this class:

	class MediaDeviceThread(threading.Thread):

	    def __init__(self):
		threading.Thread.__init__(self)
		self.bus = SystemBus()
		try:
		    self.dev = self.bus.get('org.freedesktop.UDisks2', '/org/freedesktop/UDisks2/drives/TSSTcorp_CDDVDW_SE_S084C_SATASLIM00003008cae')
		    #self.dev = self.bus.get('org.freedesktop.UDisks2', '/org/freedesktop/UDisks/devices/sr0')
		except KeyError:
		    print "CD LW not connected"
		    quit()
		self.media = self.dev.MediaAvailable

	    def _print(*a):
		print a

	    def run(self):
		with self.dev.PropertiesChanged.connect(self._print) as d:
		    if self.media:
		        print "Media still inserted..."
		        self.dev.Eject()
		    GObject.MainLoop().run()

Exception:

	self.dev.Eject()
		  File "/home/pi/jukebox/jukebox/local/lib/python2.7/site-packages/pydbus/proxy_method.py", line 61, in __call__
		    self._iface_name, self.__name__, GLib.Variant(self._sinargs, args), GLib.VariantType.new(self._soutargs),
		  File "/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py", line 240, in __new__
		    (v, rest_format, _) = creator._create(format_string, [value])
		  File "/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py", line 129, in _create
		    return self._create_tuple(format, args)
		  File "/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py", line 168, in _create_tuple
		    raise TypeError('tuple type string not closed with )')
		TypeError: tuple type string not closed with )

Versions (rpi jessie/armhf8):

pydbus (0.5.1)
python-gi:
  Installed: 3.14.0-1
  Candidate: 3.14.0-1
  Version table:
 *** 3.14.0-1 0
        500 http://mirrordirector.raspbian.org/raspbian/ jessie/main armhf Packages
        100 /var/lib/dpkg/status

**Comment by LEW21** [comment]
org.freedesktop.UDisks2.Drive.Eject requires an argument. It's signature - as reported by help(d.Eject) - is:

    Eject(options:a{sv})

More information: https://udisks.freedesktop.org/docs/latest/gdbus-org.freedesktop.UDisks2.Drive.html#gdbus-method-org-freedesktop-UDisks2-Drive.Eject

However, this exception's message is completely useless. I've comitted a fix, so that we'll throw a useful exception in the case of bad number of arguments. https://github.com/LEW21/pydbus/commit/fafecf9f6646793d772ee4a55b96841e109a91c2

**Comment by bendiken** [comment]
Just ran into this myself. @LEW21, would it be possible to push out a new release that includes the fix in fafecf9f6646793d772ee4a55b96841e109a91c2?

**Comment by LEW21** [comment]
I think I'll push a new release in a week from now.
