### ISSUE TITLE
Can't get the connection name that originated a method call

### ISSUE THREAD

**Issue by catern** [LEW21/pydbus#13]
As far as I can tell, it's not possible to get the connection name that originated a method call (when publishing an object). This makes it impossible to authenticate the caller based on their UID or other attributes.

**Comment by akruis** [comment]
I had a similar problem and hacked pydbus a bit. See https://github.com/akruis/pydbus/blob/master/pydbus/tests/publish_async.py for an example.
I'll create a pull request, once I performed some more tests.

**Comment by LEW21** [comment]
Solved with https://github.com/LEW21/pydbus/commit/8e5d4d9a0712f92dfc60fce4a17f01a7478c10fa and https://github.com/LEW21/pydbus/commit/39c4b8e2c11c434a7e134fe801a42178faf741e9.
