### ISSUE TITLE
Recommendations? Moving from 0.2 -> 0.5.1 ... Should I use master instead?

### ISSUE THREAD

**Issue by bossjones** [LEW21/pydbus#14]
Hey @LEW21 been a while since I got to work on the dbus aspect of my project, I've been stuck fixing some Gstreamer wonky-ness, but I'm finally back and I'm looking at upgrading from pydbus `0.2` -> `0.5.1`. I noticed that `0.5.1` was created about 28 days ago at the time of me writing this .... but I see that there have been several commits to master since then. Do you recommend me using the released version currently or should I start playing with the changes you've made in master ( assuming that contains even more fixes than `0.5.1` ).

Thanks for all of your hard work on this project!!! It is super super helpful!

**Comment by LEW21** [comment]
There was only one real commit since 0.5.1 - https://github.com/LEW21/pydbus/commit/fafecf9f6646793d772ee4a55b96841e109a91c2 

It simply raises a more obvious exception when you call a method with a bad number of arguments.

Therefore, it doesn't really matter if you use 0.5.1 or master.

**Comment by bossjones** [comment]
Thanks for the tip 👍 ! Closing this guy now @LEW21
