### ISSUE TITLE
Watch for new systemd jobs example.

### ISSUE THREAD

**Issue by LaPriWa** [LEW21/pydbus#18]
Hello,

I'm new to pydbus and I think it's great. 

But I have a little problem with one of the examples as written above:

I executed the code exactly as it is written on https://github.com/LEW21/pydbus. It always throws an syntax error after **systemd.JobNew.connect(print)** or **systemd.JobNew.connect = print**.

What could be the reason for that issue.

**Comment by LEW21** [comment]
Hi,

1. Do you have pydbus 0.3 or newer?
2. Can you copy & paste the full error message?

**Comment by heftig** [comment]
Probably because `print` is a statement in Python 2. This can be fixed by starting the example with:
```python
from __future__ import print_function
```

**Comment by LaPriWa** [comment]
Thank you very much for your immediate reaction. In fact importing the print function via 
`from __future__ import print_function` solved the problem instantaneously.
