### ISSUE TITLE
GLib 2.46 is currently required, can we target 2.40.2?

### ISSUE THREAD

**Issue by hh** [LEW21/pydbus#20]
Along the lines of #4 GLib is something very hard to upgrade and you are usually stuck with what is on the system. 2.46 is fairly recent (less than a year?):

https://en.wikipedia.org/wiki/GLib#Releases
https://download.gnome.org/sources/glib/2.46/

Is there something we could look into to bringing the requiement down to what is available on common stable systems? Maybe the specific method calls in 2.46? 

https://developer.gnome.org/glib/2.46/api-index-2-46.html

Debian Stable is at 2.42:

https://www.debian.org/releases/stable/
https://www.debian.org/releases/jessie/
https://packages.debian.org/jessie/libglib2.0-0

Ubuntu LTS Releases doen't have it until Xenial/16.04, the previous stable is at 2.40.2:

https://wiki.ubuntu.com/Releases
https://launchpad.net/ubuntu/%2Bsource/glib2.0

12.04 LTS until April 2017 is at 2.32.4
https://launchpad.net/ubuntu/precise/+source/glib2.0
14.04 LTS until April 2019 is at 2.40.2
https://launchpad.net/ubuntu/trusty/+source/glib2.0

Redhat and Centos are probably pretty  far back as well.

**Comment by LEW21** [comment]
No, it's unfortunately impossible. 2.46 contains a patch - https://bugzilla.gnome.org/show_bug.cgi?id=656325 - that makes publishing objects possible.

**Comment by hh** [comment]
Is there a way to detect the version of GLib at runtime to offer appropriate an error message?
Might prove useful to those who haven't pinned to 0.3.0 and hit this upgrade.

**Comment by LEW21** [comment]
0.3.0 does not support publishing objects at all, so this error can happen only for people using 0.5's features.

I guess I can catch the TypeError and raise my own exception about the GLib version instead.

**Comment by LEW21** [comment]
Error message added in https://github.com/LEW21/pydbus/commit/36fd03ee98a9b0b9502f8fced6de1ae40360fddc.

**Comment by pankit** [comment]
@LEW21 : Could you tell me how I can check the GLib version used? I installed GLib 2.46.
Also, is it available as an RPM to be installed?

**Comment by troolee** [comment]
Hi @LEW21

Same here... Trying to use pydbus for bluez on rpi3. Upgraded glib from backports to 2.48. Having the same error.
