### ISSUE TITLE
How to create Variant type?

### ISSUE THREAD

**Issue by rahvin74** [LEW21/pydbus#23]
Maybe I missed it in the Tutorial and the Docs, but I can't seem to see how to create a variant type.

In the Tutorial, it says that dbus arrays map to python lists, dbus structs map to python tuples, and dbus dictionaries map to Python dictionaries. It mentions that dbus has a Variant type, but doesn't tell me what python type it maps to.

I have a dbus method, which takes a Variant, that I am trying to call, but it is failing for me.

I've tried simply passing in the value (which is a string), I've tried making it a Tuple, and I've tried creating my own GLib.Variant, all to no avail.

What am I missing?

(Let me know if you need more info.)

Thanks!

Adam

**Comment by LEW21** [comment]
Hi,

GLib.Variant("dbus type string", value) should work. If it does not, please give me the full XML signature of the method you're trying to call. (You can retrieve object's interface XML description by using .Introspect() method.)

**Comment by rahvin74** [comment]
Thanks for the prompt response! You're awesome!

I'll give your advice a try and let you know if it works or not.

Thanks!

Adam

**Comment by rahvin74** [comment]
Looks like GLib.Variant('s', value) worked!

Thanks a lot!

Adam

**Comment by LEW21** [comment]
No problem :)
