### ISSUE TITLE
cannot SessionBus().get(".Flatpak")

### ISSUE THREAD

**Issue by muelli** [LEW21/pydbus#25]
```
In [18]: pydbus.SessionBus().get(".Flatpak")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-99fd72f277f3> in <module>()
----> 1 pydbus.SessionBus().get(".Flatpak")

/tmp/gks/local/lib/python2.7/site-packages/pydbus/proxy.pyc in get(self, bus_name, object_path)
     45                         raise KeyError("no such object")
     46 
---> 47                 return CompositeInterface(introspection)(self, bus_name, object_path)
     48 
     49 class ProxyObject(object):

/tmp/gks/local/lib/python2.7/site-packages/pydbus/proxy.pyc in CompositeInterface(introspection)
    102 
    103         ifaces = sorted([x for x in introspection if x.tag == "interface"], key=lambda x: int(x.attrib["name"].startswith("org.freedesktop.DBus.")))
--> 104         CompositeObject.__bases__ = tuple(Interface(iface) for iface in ifaces)
    105         CompositeObject.__name__ = "<CompositeObject>"
    106         CompositeObject.__qualname__ = "<CompositeObject>(" + "+".join(x.__name__ for x in CompositeObject.__bases__) + ")"

TypeError: can only assign non-empty tuple to CompositeObject.__bases__, not ()

In [19]:
```

Getting ".Notifications" works, though.

I expected to be able to talk the Flatpak service on the bus.

In any case, the error message is not helpful.

**Comment by LEW21** [comment]
You're trying to use /org/freedesktop/Flatpak object, and I don't think it exports any interfaces. Probably you should use .get(".Flatpak", "SessionHelper") - which is the /org/freedesktop/Flatpak/SessionHelper - or some other subobject (I can't find any Flatpak's API docs, so no idea if there are any other useful ones).

Of course I should raise a more useful exception in this case.

**Comment by muelli** [comment]
Ah, right. So this works better:

```
In [60]: bus.get(".Flatpak", "/org/freedesktop/Flatpak/Development")
Out[60]: <DBUS.<CompositeObject>(org.freedesktop.Flatpak.Development+org.freedesktop.DBus.Properties+org.freedesktop.DBus.Introspectable+org.freedesktop.DBus.Peer) at 0x7f32ec08ba50>
```

I didn't know about that syntax, although it's in get's docstring...  I guess I've only looked at the example and not the signature *blush*.

I'm by no means an export in dbus, but d-feet knows that the "org.freedesktop.Flatpak" service has placed an object on the bus. My naïve guess is that the library could thus very well locate the object.
In any case, the error message does not convey that an object path has been tried and that no object could be found.  I think it would improve the discoverability of the library for people like me who tinker around by trial and error in ipython.

Another issue, probably not related, is that adding null-bytes seems to be required.
```
In [70]: bus.get(".Flatpak", "/org/freedesktop/Flatpak/Development").HostCommand('/', ['ls'], {}, {}, 0)
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-70-79c94c9b1516> in <module>()
----> 1 bus.get(".Flatpak", "/org/freedesktop/Flatpak/Development").HostCommand('/', ['ls'], {}, {}, 0)

/tmp/gks/local/lib/python2.7/site-packages/pydbus/proxy_method.pyc in __call__(self, instance, *args)
     60                         instance._bus_name, instance._path,
     61                         self._iface_name, self.__name__, GLib.Variant(self._sinargs, args), GLib.VariantType.new(self._soutargs),
---> 62 			0, instance._bus.timeout, None).unpack()
     63 
     64                 if len(self._outargs) == 0:

Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: No command 272c30 given!!1 - *arg_argv[0] == 0 (16)

In [71]: bus.get(".Flatpak", "/org/freedesktop/Flatpak/Development").HostCommand('/\x00', ['ls\x00'], {}, {}, 0)
Out[71]: 17L

In [72]: 
```

If that's an issue with Flatpak's signature, I'll happily report it over there.

**Comment by LEW21** [comment]
That looks like an issue in Flatpak, I haven't met any other API requiring null bytes in the strings.

**Comment by LEW21** [comment]
Error message fixed in https://github.com/LEW21/pydbus/commit/1291c66f6b96a8042eb070505b44313a152f4cb0.

**Comment by smcv** [comment]
This appears to be a difference between byte-arrays-as-bytestrings, and proper Unicode strings.

D-Bus does not have a built-in data type for "bytestrings": byte-arrays that represent a string with no embedded `'\0'` but no other constraints (and in particular no guarantee of being UTF-8). Unfortunately, lots of data structures in Unix, including filenames and environment variable names and values, are `'\0'`-terminated bytestrings in any or no character set, which I assume is why Flatpak is doing this.

GVariant has a convention of representing a bytestring like `"foo"` as a 4-byte array `@ay ['f', 'o', 'o', '\0']`. If you do this, C clients can get a valid C `const char *` by looking into the payload of the D-Bus message or the GVariant, with no copying; if you don't, they have to use `g_strndup()` or similar, because there is no guarantee that the next byte after the end of the byte-array will be `'\0'`

The D-Bus core protocol has adopted this convention for the `LinuxSecurityLabel` value in the hash table returned by `GetConnectionCredentials()`, although the older `GetConnectionSELinuxContext()` method doesn't do it.

**Comment by LEW21** [comment]
Reopening until we finish the discussion with Flatpak developers.

**Comment by muelli** [comment]
So what's the result of the discussion then?

Will pydbus make it more natural to call the service?

**Comment by LEW21** [comment]
As discussed in #27, it's a bug in glib, on the Flatpak's side, so I can't do anything about it here. I'm going to report this bug to the Glib's bug tracker, and hopefully write a patch, soon.
