### ISSUE TITLE
Unpublish/Remove object from bus

### ISSUE THREAD

**Issue by exsypher** [LEW21/pydbus#26]
Hi,

I can publish an object with the bus.publish(..) method and I also managed to publish an object on demand with bus.register_object(...). But how can I unpublish/remove/unregister an object?
I hoped the return value of the register_object method can help me there by just calling another "unregister()" or so from it, but that doesn't seem to be available..
Thanks in advance

**Comment by LEW21** [comment]
You can use it as a context manager:

```python
with bus.publish(...):
    # whatever
# it is unpublished now
```

You can also use .unpublish() on the object returned from publish().

**Comment by exsypher** [comment]
Thank you, using .unregister() of the register_object() return value also works, was a mistake in my code...
Sorry !
