### ISSUE TITLE
New release tag

### ISSUE THREAD

**Issue by abrauchli** [LEW21/pydbus#32]
It'd be great to have a new release tag with the new features that are currently in master.
(It would make my workflow much easier to have those available from pip as e.g. 0.5.2)

Thanks a lot

**Comment by romlr** [comment]
+1
and thanks a lot anyway to LEW21 for maintaining that very useful project!

**Comment by LEW21** [comment]
Done. https://pypi.python.org/pypi/pydbus/0.6.0

**Comment by abrauchli** [comment]
Awesome, thanks a lot!
