### ISSUE TITLE
python3 required?

### ISSUE THREAD

**Issue by xdgc** [LEW21/pydbus#4]
pydbus seems to require python 3. (At minimum, it appears to use function annotations.) Could you either: (1) remove the py3 dependency, or (2) add a note to the readme that py3 is required? Thanks.

**Comment by nathan-hoad** [comment]
I've removed the annotations as a test, and it appears to support python 2 just fine apart from that. Is there a reason the annotations can't be removed? They don't appear to be used that I can see.

**Comment by LEW21** [comment]
Thanks for the report, I've added Python 2 support and released new version to the PyPI.

I was hoping nobody uses Python 2 anymore, but I see sadly this is not the case.

**Comment by xdgc** [comment]
Thanks! The thing is, Python 2 isn't just an old version — it's probably still more common than 3 since most people are using stock distributions.  And it's not always easy to move a project from 2 to 3, so use of 2 isn't going to drop significantly off until major distributions make their move to Python 3 first.

I'm not trying to hold back momentum though. No argument from me to moving ahead into Python 3, I just like it to be clear if it's required. :)
