### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by mxa** [LEW21/pydbus#6]
$ ./setup.py 
   Traceback (most recent call last):
     File "./setup.py", line 3, in <module>
       from setuptools import setup, find_packages
   ImportError: No module named setuptools

I have setuptools installed though.

    sudo apt-get install python-setuptools
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    python-setuptools is already the newest version.
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by LEW21** [comment]
Install python3-setuptools.

**Comment by mxa** [comment]
Thanks
